"""stage6 7 delivery batches monthly rates

Revision ID: ae90bd431820
Revises: 54a715dce242
Create Date: 2026-09-18 07:29:25.242447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae90bd431820'
down_revision = '54a715dce242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_consolidated', sa.Boolean(), nullable=True),
    sa.Column('consolidation_type', sa.String(length=20), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('rate_per_cbm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('shipment_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('payment_settled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_note', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_arrival_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estimated_arrival_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('delivery_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_batch_id', 'shipment_batches', ['batch_id'], ['id'])
        batch_op.create_foreign_key('fk_sales_delivery_id', 'deliveries', ['delivery_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_delivery_id', type_='foreignkey')
        batch_op.drop_constraint('fk_sales_batch_id', type_='foreignkey')
        batch_op.drop_column('delivery_id')
        batch_op.drop_column('actual_shipping_cost')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('estimated_arrival_end')
        batch_op.drop_column('estimated_arrival_start')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_column('variant_note')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('estimated_shipping_cost')

    op.drop_table('shipment_batches')
    op.drop_table('monthly_shipping_rates')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
