"""stage8 per-sale shipping settlement

Revision ID: b11bd6d0ad19
Revises: ae90bd431820
Create Date: 2026-09-18 20:16:54.460428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11bd6d0ad19'
down_revision = 'ae90bd431820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_payment_settled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_payment_settled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('shipping_payment_settled_at')
        batch_op.drop_column('shipping_payment_settled')

    # ### end Alembic commands ###
